stages:
    - preevaluation

variables:
    TAG_NAME: cibuild-${CI_PIPELINE_IID}
    RELEASE_NAME: CI build ${CI_PIPELINE_IID}
    PACKAGE_REGISTRY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic

default:
    before_script:
        - source scripts/env.sh
    id_tokens:
        CI_JOB_JWT:
            aud: https://git.uni-paderborn.de

.cheap_job:
    rules:
        - if: always
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event' # Run for all merge-requests (even drafts)
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on the main branch

.expensive_job:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TITLE !~ /^Draft:/ # Run for non-draft merge requests
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on the main branch


.synthesis:
    extends: .expensive_job
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "${STST_EXAMPLE}" "${STST_EXECUTABLE}"
    artifacts:
        when: always
        paths:
            - "build/examples/${STST_EXAMPLE}/${STST_EXECUTABLE}"
            - "build/examples/${STST_EXAMPLE}/${STST_EXECUTABLE}.prj/reports"
            - "build/examples/${STST_EXAMPLE}/${STST_EXECUTABLE}.prj/quartuserr.tmp"
            - "build/examples/${STST_EXAMPLE}/${STST_EXECUTABLE}.prj/quartus_sh_compile.log"
            - "build/examples/${STST_EXAMPLE}/${STST_EXECUTABLE}.tar.gz"

# =============
# Preevaluation
# =============

documentation:
    extends: .cheap_job
    stage: preevaluation
    tags:
        - docker-shared
    image: alpine
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - doxygen/html